version: "3.8"

services:
  app:
    image: golang:1.19-alpine
    command: sh -c "go mod download && go run helloworld.go"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app